import type { TemplateInputConfig, Placement } from "@/lib/coc-inputs/types";

/** Element id prefix for elements generated by "Place on template" (re-running replaces them). */
export const AUTO_PREFIX = "de-";

type AnyEl = Record<string, unknown> & { id: string; type: string; fieldName?: string };

const baseStyle = (p: Placement) => ({
  fontFamily: "Helvetica",
  fontSize: p.fontSize ?? 10,
  bold: p.bold ?? false,
  align: p.align ?? "center",
  valign: "middle",
  padding: 1,
  color: "#0b3d91",
});

/**
 * Convert the data-entry configuration's placements (and system stamps such as the serial number)
 * into template designer elements, grouped by 1-based page number.
 */
export function buildPlacementElements(cfg: TemplateInputConfig): Map<number, AnyEl[]> {
  const out = new Map<number, AnyEl[]>();
  const push = (page: number, el: AnyEl) => {
    const list = out.get(page) ?? [];
    list.push(el);
    out.set(page, list);
  };

  for (const s of cfg.sections) {
    for (const f of s.fields) {
      (f.placements ?? []).forEach((p, i) => {
        const common = { id: `${AUTO_PREFIX}${f.key}-${i + 1}`, name: f.label, x: p.x, y: p.y, width: p.w, height: p.h };
        if (f.type === "photo") {
          push(p.page, { ...common, type: "image", assetId: null, fieldName: f.key, fit: "contain" });
        } else if (f.type === "checkbox") {
          push(p.page, { ...common, type: "checkbox", fieldName: f.key, checked: false, binding: {} });
        } else {
          push(p.page, { ...common, type: "field", fieldName: f.key, binding: {}, style: baseStyle(p) });
        }
      });
    }
  }
  (cfg.stamps ?? []).forEach((st, i) => {
    push(st.page, {
      id: `${AUTO_PREFIX}${st.fieldName}-p${st.page}-${i + 1}`,
      name: st.fieldName,
      type: "field",
      fieldName: st.fieldName,
      x: st.x,
      y: st.y,
      width: st.w,
      height: st.h,
      binding: {},
      style: baseStyle(st),
    });
  });
  return out;
}

/** Number of placements defined in a configuration (fields + stamps). */
export function countPlacements(cfg: TemplateInputConfig): number {
  return cfg.sections.reduce((n, s) => n + s.fields.reduce((m, f) => m + (f.placements?.length ?? 0), 0), 0) + (cfg.stamps?.length ?? 0);
}
