import type { D365ProductionOrder, D365SalesOrderLine } from "./types";

export const MOCK_PRODUCTION_ORDERS: D365ProductionOrder[] = [
  {
    ProductionOrder: "HSIN-000015",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112",
    CustomerAccount: "HSIN",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Started",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008214",
    SalesOrder: "SO-002859",
    SalesLine: "4.0",
    BatchNumber: "HS-B24-0015",
    SerialNumber: "SN-HSIN-000015",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-10-18",
  },
  {
    ProductionOrder: "HSIN-000014",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112",
    CustomerAccount: "HSIN",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "ReportedFinished",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008214",
    SalesOrder: "SO-002859",
    SalesLine: "3.0",
    BatchNumber: "HS-B24-0014",
    SerialNumber: "SN-HSIN-000014",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-10-15",
  },
  {
    ProductionOrder: "HSIN-000012",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112",
    CustomerAccount: "HSIN",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Released",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008214",
    SalesOrder: "SO-002859",
    SalesLine: "2.0",
    BatchNumber: "HS-B24-0012",
    SerialNumber: "SN-HSIN-000012",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-10-10",
  },
  {
    ProductionOrder: "HSIN-000011",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112",
    CustomerAccount: "HSIN",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Completed",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008214",
    SalesOrder: "SO-002859",
    SalesLine: "1.0",
    BatchNumber: "HS-B24-0011",
    SerialNumber: "SN-HSIN-000011",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-10-06",
  },
  {
    ProductionOrder: "HGCN-000841",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 (China Production)",
    CustomerAccount: "HGCN",
    dataAreaId: "HGCN",
    ProductionOrderStatus: "Completed",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGY CHINA CO LTD",
    CustomerPO: "4509009981",
    SalesOrder: "SO-CN-0982",
    SalesLine: "1.0",
    BatchNumber: "CN-B24-0841",
    SerialNumber: "SN-HGCN-000841",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-11-12",
  },
  {
    ProductionOrder: "HSDK-000192",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 (Denmark Plant)",
    CustomerAccount: "HSDK",
    dataAreaId: "HSDK",
    ProductionOrderStatus: "Completed",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND SYSTEMS A/S",
    CustomerPO: "4509001122",
    SalesOrder: "SO-DK-0192",
    SalesLine: "1.0",
    BatchNumber: "DK-B24-0192",
    SerialNumber: "SN-HSDK-000192",
    DrawingNumber: "DWG-29110478",
    Revision: "Rev 05",
    Quantity: 1,
    UnitOfMeasure: "pcs",
    RemainingQuantity: 1,
    Specification: "0068-7211 / 0069-2093 Latest version",
    DeliveryDate: "2023-12-01",
  },
  {
    ProductionOrder: "PO-2026-10710747",
    ItemNumber: "1071.0747",
    ItemDescription: "High Pressure Flexible Hose Assembly DN16 - 1071.0747",
    CustomerAccount: "CUST-HSIN",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Completed",
    CustomerPartNumber: "160072",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    DeliveryAddressName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "PO-HSIN-74721",
    SalesOrder: "SO-74721",
    SalesLine: "1.0",
    BatchNumber: "HS-B24-0747",
    SerialNumber: "SN-1071-0747-01",
    DrawingNumber: "DWG-1071-0747",
    Revision: "Rev 01",
    Quantity: 100,
    UnitOfMeasure: "Pcs",
    RemainingQuantity: 100,
    Specification: "ISO 9001:2015 / EN 853 2SN, Max WP 350 bar",
    DeliveryDate: "2026-09-28",
  },
  {
    ProductionOrder: "PO-2026-00101",
    ItemNumber: "HS-HOSE-050-2SN",
    ItemDescription: 'Hydraulic Hose Assembly 1/2" 2SN BSP Female 1200mm',
    CustomerAccount: "CUST-JCB",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Released",
    CustomerName: "JCB India Limited",
    CustomerPO: "JCB-PO-88214",
    SalesOrder: "SO-10923",
    SalesLine: "1.0",
    BatchNumber: "HS-B24-091",
    SerialNumber: "SN-2026-9011",
    DrawingNumber: "DWG-1070-0049",
    Revision: "Rev 02",
    Quantity: 250,
    UnitOfMeasure: "Pcs",
    RemainingQuantity: 250,
    Specification: "DIN EN 853 2SN, Max WP 275 bar",
    DeliveryDate: "2026-09-20",
  },
  {
    ProductionOrder: "PO-2026-00102",
    ItemNumber: "HS-FIT-316-0808",
    ItemDescription: 'Stainless Steel 316 Swivel Female Fitting 1/2" x 1/2"',
    CustomerAccount: "CUST-CAT",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Started",
    CustomerName: "Caterpillar India Pvt Ltd",
    CustomerPO: "CAT-IN-4921",
    SalesOrder: "SO-10924",
    SalesLine: "1.0",
    BatchNumber: "SS-316-902",
    SerialNumber: "SN-2026-9012",
    DrawingNumber: "DWG-FIT-316-08",
    Revision: "Rev 01",
    Quantity: 500,
    UnitOfMeasure: "Pcs",
    RemainingQuantity: 500,
    Specification: "ASTM A276 / AISI 316 Stainless Steel",
    DeliveryDate: "2026-09-22",
  },
  {
    ProductionOrder: "PO-2026-00103",
    ItemNumber: "HS-FLG-6000-100",
    ItemDescription: 'High Pressure Code 62 Flange 1" SAE 6000 PSI',
    CustomerAccount: "CUST-VOLVO",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "ReportedFinished",
    CustomerName: "Volvo Construction Equipment India",
    CustomerPO: "VCE-77312",
    SalesOrder: "SO-10925",
    SalesLine: "2.0",
    BatchNumber: "FL-B24-114",
    DrawingNumber: "DWG-SAE-6000-10",
    Revision: "Rev 03",
    Quantity: 120,
    UnitOfMeasure: "Pcs",
    RemainingQuantity: 120,
    Specification: "SAE J518-2 Code 62, 420 bar WP",
    DeliveryDate: "2026-09-25",
  },
  {
    ProductionOrder: "PO-2026-00104",
    ItemNumber: "HS-TUBE-10MM-ST",
    ItemDescription: "Hydraulic Seamless Precision Steel Tube 10mm OD x 1.5mm",
    CustomerAccount: "CUST-AL",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Completed",
    CustomerName: "Ashok Leyland Defence",
    CustomerPO: "AL-DIR-33291",
    SalesOrder: "SO-10926",
    SalesLine: "1.0",
    BatchNumber: "BT-B24-044",
    DrawingNumber: "DWG-TUBE-1015-E235",
    Revision: "Rev 00",
    Quantity: 1000,
    UnitOfMeasure: "Mtr",
    RemainingQuantity: 1000,
    Specification: "EN 10305-4 E235+N Phosphate & Oiled",
    DeliveryDate: "2026-09-28",
  },
  {
    ProductionOrder: "PO-2026-00105",
    ItemNumber: "HS-QDC-7241-08",
    ItemDescription: 'Quick Disconnect Hydraulic Coupling ISO 7241-1 A 1/2"',
    CustomerAccount: "CUST-TH",
    dataAreaId: "HSIN",
    ProductionOrderStatus: "Completed",
    CustomerName: "Tata Hitachi Construction Machinery",
    CustomerPO: "TH-PO-01924",
    SalesOrder: "SO-10927",
    SalesLine: "3.0",
    BatchNumber: "QD-B24-210",
    DrawingNumber: "DWG-QDC-7241A",
    Revision: "Rev 02",
    Quantity: 75,
    UnitOfMeasure: "Pcs",
    RemainingQuantity: 75,
    Specification: "ISO 7241-1 A Standard, Carbon Steel Trivalent Zinc",
    DeliveryDate: "2026-09-30",
  },
];

export const MOCK_SALES_ORDER_LINES: D365SalesOrderLine[] = [
  // 29110478R05 - Main tank assembly V112
  {
    SalesOrder: "SO-002859",
    LineNumber: "1.0",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112",
    CustomerAccount: "HSIN",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008214",
    ExternalItemNumber: "160072",
    Quantity: 10,
    UnitOfMeasure: "pcs",
    DeliveryDate: "2023-10-18",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-002860",
    LineNumber: "1.0",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 (Standard Batch)",
    CustomerAccount: "HSIN",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509008299",
    ExternalItemNumber: "160072-V112",
    Quantity: 25,
    UnitOfMeasure: "pcs",
    DeliveryDate: "2023-11-05",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-002861",
    LineNumber: "2.0",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 - Spare Series",
    CustomerAccount: "HSIN",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "4509009100",
    ExternalItemNumber: "160072-SP",
    Quantity: 5,
    UnitOfMeasure: "pcs",
    DeliveryDate: "2023-11-20",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-CN-0982",
    LineNumber: "1.0",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 (China Production)",
    CustomerAccount: "HGCN",
    CustomerName: "VESTAS WIND TECHNOLOGY CHINA CO LTD",
    CustomerPO: "4509009981",
    ExternalItemNumber: "160072-CN",
    Quantity: 15,
    UnitOfMeasure: "pcs",
    DeliveryDate: "2023-11-12",
    dataAreaId: "HGCN",
  },
  {
    SalesOrder: "SO-DK-0192",
    LineNumber: "1.0",
    ItemNumber: "29110478R05",
    ItemDescription: "Main tank assembly V112 (Denmark Plant)",
    CustomerAccount: "HSDK",
    CustomerName: "VESTAS WIND SYSTEMS A/S",
    CustomerPO: "4509001122",
    ExternalItemNumber: "160072-DK",
    Quantity: 20,
    UnitOfMeasure: "pcs",
    DeliveryDate: "2023-12-01",
    dataAreaId: "HSDK",
  },

  // 1070.0049 - Hydraulic Assembly DN12 (Customer Part 29107156)
  {
    SalesOrder: "SO-1070-01",
    LineNumber: "1.0",
    ItemNumber: "1070.0049",
    ItemDescription: "Hydraulic Assembly DN12 - 1070.0049",
    CustomerAccount: "HSIN",
    CustomerName: "JCB India Limited",
    CustomerPO: "4509008214",
    ExternalItemNumber: "29107156",
    Quantity: 200,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-15",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-1070-02",
    LineNumber: "2.0",
    ItemNumber: "1070.0049",
    ItemDescription: "Hydraulic Assembly DN12 - 1070.0049",
    CustomerAccount: "HSIN",
    CustomerName: "JCB India Limited",
    CustomerPO: "4509008990",
    ExternalItemNumber: "29107156",
    Quantity: 100,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-22",
    dataAreaId: "HSIN",
  },

  // 1071.0747 - High Pressure Flexible Hose Assembly DN16
  {
    SalesOrder: "SO-74721",
    LineNumber: "1.0",
    ItemNumber: "1071.0747",
    ItemDescription: "High Pressure Flexible Hose Assembly DN16 - 1071.0747",
    CustomerAccount: "HSIN",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    DeliveryAddressName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "PO-HSIN-74721",
    ExternalItemNumber: "160072",
    Quantity: 100,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-28",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-74722",
    LineNumber: "1.0",
    ItemNumber: "1071.0747",
    ItemDescription: "High Pressure Flexible Hose Assembly DN16 - 1071.0747",
    CustomerAccount: "HSIN",
    CustomerName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    DeliveryAddressName: "VESTAS WIND TECHNOLOGYS INDIA PVT LTD",
    CustomerPO: "PO-HSIN-74755",
    ExternalItemNumber: "160072-V",
    Quantity: 50,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-10-02",
    dataAreaId: "HSIN",
  },

  // Other standard product numbers
  {
    SalesOrder: "SO-10923",
    LineNumber: "1.0",
    ItemNumber: "HS-HOSE-050-2SN",
    ItemDescription: 'Hydraulic Hose Assembly 1/2" 2SN BSP Female 1200mm',
    CustomerAccount: "CUST-JCB",
    CustomerName: "JCB India Limited",
    CustomerPO: "JCB-PO-88214",
    ExternalItemNumber: "29107156",
    Quantity: 250,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-20",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-10924",
    LineNumber: "1.0",
    ItemNumber: "HS-FIT-316-0808",
    ItemDescription: 'Stainless Steel 316 Swivel Female Fitting 1/2" x 1/2"',
    CustomerAccount: "CUST-CAT",
    CustomerName: "Caterpillar India Pvt Ltd",
    CustomerPO: "CAT-IN-4921",
    ExternalItemNumber: "CAT-4921-X",
    Quantity: 500,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-22",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-10925",
    LineNumber: "2.0",
    ItemNumber: "HS-FLG-6000-100",
    ItemDescription: 'High Pressure Code 62 Flange 1" SAE 6000 PSI',
    CustomerAccount: "CUST-VOLVO",
    CustomerName: "Volvo Construction Equipment India",
    CustomerPO: "VCE-77312",
    ExternalItemNumber: "VCE-77312-A",
    Quantity: 120,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-25",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-10926",
    LineNumber: "1.0",
    ItemNumber: "HS-TUBE-10MM-ST",
    ItemDescription: "Hydraulic Seamless Precision Steel Tube 10mm OD x 1.5mm",
    CustomerAccount: "CUST-AL",
    CustomerName: "Ashok Leyland Defence",
    CustomerPO: "AL-DIR-33291",
    ExternalItemNumber: "AL-99821",
    Quantity: 1000,
    UnitOfMeasure: "Mtr",
    DeliveryDate: "2026-09-28",
    dataAreaId: "HSIN",
  },
  {
    SalesOrder: "SO-10927",
    LineNumber: "3.0",
    ItemNumber: "HS-QDC-7241-08",
    ItemDescription: 'Quick Disconnect Hydraulic Coupling ISO 7241-1 A 1/2"',
    CustomerAccount: "CUST-TH",
    CustomerName: "Tata Hitachi Construction Machinery",
    CustomerPO: "TH-PO-01924",
    ExternalItemNumber: "TH-QDC-019",
    Quantity: 75,
    UnitOfMeasure: "Pcs",
    DeliveryDate: "2026-09-30",
    dataAreaId: "HSIN",
  },
];

export function getMockSalesOrders(itemNumber: string, company?: string, salesOrder?: string): D365SalesOrderLine[] {
  const cleanItem = (itemNumber || "").trim().toLowerCase();
  const cleanComp = (company || "").trim().toLowerCase();
  const cleanSO = (salesOrder || "").trim().toLowerCase();
  const isAllComp = !cleanComp || cleanComp === "all";

  // First priority: exact match on ItemNumber (and SalesOrder if provided)
  let matched = MOCK_SALES_ORDER_LINES.filter((so) => {
    const soItem = so.ItemNumber.toLowerCase();
    const itemMatch = soItem === cleanItem;
    const compMatch = isAllComp || (so.dataAreaId?.toLowerCase() === cleanComp) || (so.CustomerAccount?.toLowerCase().includes(cleanComp));
    const soMatch = !cleanSO || so.SalesOrder.toLowerCase() === cleanSO;
    return itemMatch && compMatch && soMatch;
  });

  // Second priority: substring match on ItemNumber only if no exact item matched and no specific SO was requested
  if (matched.length === 0 && !cleanSO) {
    matched = MOCK_SALES_ORDER_LINES.filter((so) => {
      const soItem = so.ItemNumber.toLowerCase();
      const itemMatch = soItem === cleanItem || cleanItem.includes(soItem) || soItem.includes(cleanItem);
      const compMatch = isAllComp || (so.dataAreaId?.toLowerCase() === cleanComp) || (so.CustomerAccount?.toLowerCase().includes(cleanComp));
      return itemMatch && compMatch;
    });
  }

  // If a specific reference sales order was requested, return ONLY that reference sales order line
  if (cleanSO) {
    if (matched.length === 0) {
      const comp = !isAllComp ? company!.toUpperCase() : "HSIN";
      const custName = comp === "HGCN" ? "VESTAS WIND TECHNOLOGY CHINA CO LTD" : "VESTAS WIND TECHNOLOGYS INDIA PVT LTD";
      let derivedCustomerPart = "160072";
      if (cleanItem.includes("1070.0049") || cleanItem.includes("10700049")) {
        derivedCustomerPart = "29107156";
      }
      matched = [
        {
          SalesOrder: salesOrder!.trim(),
          LineNumber: "1.0",
          ItemNumber: itemNumber,
          ItemDescription: `Assembly Specification for ${itemNumber}`,
          CustomerAccount: comp,
          CustomerName: custName,
          CustomerPO: `PO-${cleanSO.slice(-6) || "4509008214"}`,
          ExternalItemNumber: derivedCustomerPart,
          Quantity: 100,
          UnitOfMeasure: "Pcs",
          DeliveryDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
          dataAreaId: comp,
        },
      ];
    } else {
      matched = matched.filter((so) => so.SalesOrder.toLowerCase() === cleanSO);
    }
    return matched;
  }

  if (matched.length === 0 && cleanItem) {
    const baseCode = cleanItem.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
    const shortCode = baseCode.slice(-6) || "9001";
    const comp = !isAllComp ? company!.toUpperCase() : "HSIN";
    const custName = comp === "HGCN" ? "VESTAS WIND TECHNOLOGY CHINA CO LTD" : "VESTAS WIND TECHNOLOGYS INDIA PVT LTD";
    
    // Check known item mappings
    let derivedCustomerPart = "160072";
    if (cleanItem.includes("1070.0049") || cleanItem.includes("10700049")) {
      derivedCustomerPart = "29107156";
    }

    matched = [
      {
        SalesOrder: `SO-${shortCode}`,
        LineNumber: "1.0",
        ItemNumber: itemNumber,
        ItemDescription: `Assembly Specification for ${itemNumber}`,
        CustomerAccount: comp,
        CustomerName: custName,
        CustomerPO: `PO-${shortCode}-01`,
        ExternalItemNumber: derivedCustomerPart,
        Quantity: 50,
        UnitOfMeasure: "Pcs",
        DeliveryDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
        dataAreaId: comp,
      },
    ];
  }

  return matched;
}
